// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg7hgeNvlOhj9nW-8lbK41oAnQoToobNM',
    appId: '1:594585563726:web:a31f08754ee916c5a4091f',
    messagingSenderId: '594585563726',
    projectId: 'quizapp-f8baa',
    authDomain: 'quizapp-f8baa.firebaseapp.com',
    storageBucket: 'quizapp-f8baa.appspot.com',
    measurementId: 'G-CR9VVLYEZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR_t__DrqpTx-kIdLRRnydYEnog3PR2os',
    appId: '1:594585563726:android:defa54bd47f3eaa0a4091f',
    messagingSenderId: '594585563726',
    projectId: 'quizapp-f8baa',
    storageBucket: 'quizapp-f8baa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb2ILjAni4Ckx8optwflGpXquDODt9Myo',
    appId: '1:594585563726:ios:145b980dc301baafa4091f',
    messagingSenderId: '594585563726',
    projectId: 'quizapp-f8baa',
    storageBucket: 'quizapp-f8baa.appspot.com',
    iosBundleId: 'io.stelladev.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb2ILjAni4Ckx8optwflGpXquDODt9Myo',
    appId: '1:594585563726:ios:8059bd5fdbca0b27a4091f',
    messagingSenderId: '594585563726',
    projectId: 'quizapp-f8baa',
    storageBucket: 'quizapp-f8baa.appspot.com',
    iosBundleId: 'io.stelladev.quizapp.RunnerTests',
  );
}
