// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOq0Ux4a0CIux8on0b3IIq1pKOXfGaQLs',
    appId: '1:619701478555:web:cb365bfebbd4d7738e523e',
    messagingSenderId: '619701478555',
    projectId: 'loginapp-d80a9',
    authDomain: 'loginapp-d80a9.firebaseapp.com',
    storageBucket: 'loginapp-d80a9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByIyyxaj1-ZtZADrpY9piabmvtja1bLDA',
    appId: '1:619701478555:android:4948defa8b8921938e523e',
    messagingSenderId: '619701478555',
    projectId: 'loginapp-d80a9',
    storageBucket: 'loginapp-d80a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYmzLk_HD5L36kDXQv86gVJViSkzjU-0I',
    appId: '1:619701478555:ios:e478c6755133e7238e523e',
    messagingSenderId: '619701478555',
    projectId: 'loginapp-d80a9',
    storageBucket: 'loginapp-d80a9.appspot.com',
    iosClientId: '619701478555-jtds1af4rqv3ggtrs8c3hnmm8igdc68h.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYmzLk_HD5L36kDXQv86gVJViSkzjU-0I',
    appId: '1:619701478555:ios:501a8f96528fb4fc8e523e',
    messagingSenderId: '619701478555',
    projectId: 'loginapp-d80a9',
    storageBucket: 'loginapp-d80a9.appspot.com',
    iosClientId: '619701478555-jo8dddeatrprg9007u0b88h3njn1e86m.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginpage.RunnerTests',
  );
}
